// mock.js

// 引入mockjs
const Mock = require('mockjs')
// 获取 mock.Random 对象
const Random = Mock.Random
// mock新闻数据，包括新闻标题title、内容content、创建时间createdTime
const produceNewsData = function () {
 let newsList = []
 for (let i = 0; i < 20; i++) {
 let newNewsObject = {
 title: Random.ctitle(), // Random.ctitle( min, max ) 随机产生一个中文标题，长度默认在3-7之间
 content: Random.cparagraph(), // Random.cparagraph(min, max) 随机生成一个中文段落，段落里的句子个数默认3-7个
 createdTime: Random.date() // Random.date()指示生成的日期字符串的格式,默认为yyyy-MM-dd；
 }
 newsList.push(newNewsObject)
 }
 return newsList
}
// 请求该url，就可以返回newsList
Mock.mock('/mock/news', ops => {
  console.log('0----------------', ops)
})
Mock.mock('/mock/news', produceNewsData)
let webInfoJson = {
  "code": 200,
  "message": null,
  "data": {
      "id": 1,
      "webName": "POETIZE",
      "webTitle": "童话",
      "notices": "[\"POETIZE - 完整版：https://poetize.cn/article/20\",\"开源版QQ群：807489974\"]",
      "footer": "云想衣裳花想容，春风拂槛露华浓。",
      "backgroundImage": "https://file.poetize.cn/webBackgroundImage/Sara11715864931507685.jpg",
      "avatar": "https://file.poetize.cn/webAvatar/Sara116383637867956",
      "randomAvatar": null,
      "randomName": null,
      "randomCover": `[\"https://file.poetize.cn/randomCover/Sara11712577250859470.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577251035194.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577250806907.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577250907813.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577250984979.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577319942497.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577320021545.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577320111170.jpg\",\"https://file.poetize.cn/randomCover/Sara1171257732029155.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577320389639.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577365966150.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577366099546.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577366148102.jpg\",\"https://file.poetize.cn/randomCover/Sara11712577366306101.jpg\",\"https://file.poetize.cn/randomCover/Sara1171257736645913.jpg\"]",
      "ext": "{\"seasons\":[{\"date\":\"01/01\",\"text\":\"<span>元旦</span>了呢，新的一年又开始了，今年是{year}年～\"},{\"date\":\"02/14\",\"text\":\"又是一年<span>情人节</span>，{year}年找到对象了嘛～\"},{\"date\":\"03/08\",\"text\":\"今天是<span>国际妇女节</span>！\"},{\"date\":\"03/12\",\"text\":\"今天是<span>植树节</span>，要保护环境呀！\"},{\"date\":\"04/01\",\"text\":\"悄悄告诉你一个秘密～<span>今天是愚人节，不要被骗了哦～</span>\"},{\"date\":\"05/01\",\"text\":\"今天是<span>五一劳动节</span>，计划好假期去哪里了吗～\"},{\"date\":\"06/01\",\"text\":\"<span>儿童节</span>了呢，快活的时光总是短暂，要是永远长不大该多好啊…\"},{\"date\":\"09/03\",\"text\":\"<span>中国人民抗日战争胜利纪念日</span>，铭记历史、缅怀先烈、珍爱和平、开创未来。\"},{\"date\":\"09/10\",\"text\":\"<span>教师节</span>，在学校要给老师问声好呀～\"},{\"date\":\"10/01\",\"text\":\"<span>国庆节</span>到了，为祖国母亲庆生！\"},{\"date\":\"11/05-11/12\",\"text\":\"今年的<span>双十一</span>是和谁一起过的呢～\"},{\"date\":\"12/20-12/31\",\"text\":\"这几天是<span>圣诞节</span>，主人肯定又去剁手买买买了～\"}],\"mouseover\":[{\"selector\":\"#live2d\",\"text\":[\"我是一个特别固执的人，我从来不会在意别人跟我说什么，让我去做，让我去怎么做，我不管。如果，你也可以像我一样，那我觉得，这件事情，太酷辣!!!\",\"我厉害，你给我大拇哥！\",\"那些说我们的网站土的人，说抄袭的人，说我们文章拉的人，说我吃饱了撑的人，你给我大拇哥！\",\"喵喵喵？\",\"好久不见，日子过得好快呢……\",\"嘤嘤嘤～\",\"嗨～快来逗我玩吧！\",\"退、退、退\",\"很喜欢上班，有种上坟的感觉。\",\"很喜欢放假，有种刑满释放的感觉。\",\"很喜欢看评论，有一种批阅奏折的感觉。\",\"很喜欢发工资，有一种领低保的感觉。\",\"记得把我加入 Adblock 白名单哦！\"]},{\"selector\":\"#waifu-tool .fa-street-view\",\"text\":[\"喜欢换装 PLAY 吗？\",\"这次要扮演什么呢？\",\"变装！\",\"让我们看看接下来会发生什么！\"]},{\"selector\":\"#waifu-tool .fa-times\",\"text\":[\"到了要说再见的时候了吗？\",\"呜呜 QAQ 后会有期……\",\"不要抛弃我呀……\",\"我们，还能再见面吗……\",\"哼，你会后悔的！\"]}],\"pushArticleId\":20,\"click\":[{\"selector\":\"#live2d\",\"text\":[\"你看到我的小熊了吗？\",\"半山腰上的人，他还好吗？\",\"也许还没等他回过神，就又是一年春天过去\",\"风轻轻拂过半山腰，他的眼睛总有些落寞\",\"云轻轻盖过他头崖，他的眼睛总是有泪痕\",\"他在等什么 他在盼着 什么\",\"你看对面的高山多漂亮\",\"风轻轻拂过半山腰，春天时刻万物苏醒了\",\"云轻轻盖过他头崖，悲伤过去迎来朝阳\",\"他终于笑了 他终于笑了 他笑得好看\",\"传说你永远不会老去，永远不需要伪装\",\"每颗年轻的心房都对你欲盖弥彰\",\"如今北风吹，都是等待的脸庞\",\"自由的Sara啊，你知道年少的我不懂得忍让\",\"痴痴地向前望，十字路口摸不清方向\",\"如今北风吹，吹变了我的模样\",\"如今北风吹，吹散了纯粹的香味\",\"如今北风吹，预言如现实来到身旁\"]}],\"customCss\":\".aplayer-title {\\n    color: var(--fontColor) !important;\\n}\\n\\n.aplayer.aplayer-fixed {\\n    z-index: 100 !important;\\n}\"}`,
      "status": true,
      "historyAllCount": "100788",
      "historyDayCount": "244",
      "defaultStoreType": "qiniu",
      "articlePush": {
          "cover": "https://file.poetize.cn/articleCover/Sara11666527482073253",
          "id": "20",
          "title": "POETIZE - 最美博客完整版"
      },
      "version": {
          "pay": "1"
      },
      "customCss": null
  },
  "currentTimeMillis": 1725090413219
}
Mock.mock("/webInfo/getWebInfo", webInfoJson)
let listSysJson = {
  "code": 200,
  "message": null,
  "data": {
      "local.enable": "true",
      "nav.cover.dongman": "",
      "local.downloadUrl": "https://poetize.cn/static/",
      "friendCover": "https://s1.ax1x.com/2022/11/10/z9VlHs.png",
      "qiniuUrl": "https://upload.qiniup.com",
      "favorite.menu.show": "音乐,收藏夹,相册集,友链,看板娘,播放器",
      "web.blog": "1",
      "friendAvatar": "https://s1.ax1x.com/2022/11/10/z9E7X4.jpg",
      "friendWebName": "POETIZE",
      "web.index.height": "50",
      "webStaticResourcePrefix": "https://poetize.cn/static/",
      "qiniu.enable": "true",
      "web.nav.name": "首页:\uD83C\uDFE1 首页|家:\uD83D\uDC96 家|随笔:\uD83C\uDFD6️ 随笔|记录:\uD83D\uDCD2 记录|相册:\uD83D\uDCF8 相册|百宝箱:\uD83E\uDDF0 百宝箱|留言:\uD83D\uDCEA 留言|联系我:\uD83D\uDCAC 联系我|后台:\uD83D\uDCBB️ 后台|登录:登录",
      "bar.menu.show": "首页,记录,家,随笔,相册,百宝箱,留言,联系我,后台",
      "web.title": "POETIZE - 最美博客",
      "web.index.message": "true",
      "web.icon": "https://file.poetize.cn/webAvatar/Sara116383637867956",
      "store.type": "qiniu",
      "beian": "豫ICP备2021034826号-1",
      "friendIntroduction": "这是一个 Vue2 Vue3 与 SpringBoot 结合的产物～",
      "web.log": "https://file.poetize.cn/assets/Sara11724906297950627.png",
      "qiniu.downloadUrl": "https://file.poetize.cn/",
      "nav.cover.fengjing": "",
      "web.sort.select": "true",
      "space.video": "",
      "web.home.select": "true",
      "web.index": "1",
      "friendUrl": "https://poetize.cn"
  },
  "currentTimeMillis": 1725092085705
}
Mock.mock("/sysConfig/listSysConfig", listSysJson)
let  getSortJson = {
  "code": 200,
  "message": null,
  "data": [
      {
          "id": 2,
          "sortName": "生活倒影",
          "sortDescription": "记录美好生活",
          "sortType": 0,
          "priority": 1,
          "countOfSort": 9,
          "labels": [
              {
                  "id": 6,
                  "sortId": 2,
                  "labelName": "被偷走的那几年",
                  "labelDescription": "被偷走的那几年",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              {
                  "id": 20,
                  "sortId": 2,
                  "labelName": "人间百态",
                  "labelDescription": "人间百态",
                  "goodId": null,
                  "countOfLabel": 3,
                  "goodInfo": null
              }
          ]
      },
      {
          "id": 3,
          "sortName": "学习人生",
          "sortDescription": "学到老，活到老",
          "sortType": 1,
          "priority": 4,
          "countOfSort": 34,
          "labels": [
              {
                  "id": 5,
                  "sortId": 3,
                  "labelName": "Java",
                  "labelDescription": "Java",
                  "goodId": null,
                  "countOfLabel": 7,
                  "goodInfo": null
              },
              {
                  "id": 8,
                  "sortId": 3,
                  "labelName": "SpringBoot",
                  "labelDescription": "SpringBoot",
                  "goodId": null,
                  "countOfLabel": 9,
                  "goodInfo": null
              },
              {
                  "id": 15,
                  "sortId": 3,
                  "labelName": "大数据",
                  "labelDescription": "大数据",
                  "goodId": null,
                  "countOfLabel": 4,
                  "goodInfo": null
              },
              {
                  "id": 23,
                  "sortId": 3,
                  "labelName": "MySQL",
                  "labelDescription": "MySQL",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              {
                  "id": 24,
                  "sortId": 3,
                  "labelName": "Redis",
                  "labelDescription": "Redis",
                  "goodId": null,
                  "countOfLabel": 2,
                  "goodInfo": null
              },
              {
                  "id": 25,
                  "sortId": 3,
                  "labelName": "Dubbo",
                  "labelDescription": "Dubbo",
                  "goodId": null,
                  "countOfLabel": 2,
                  "goodInfo": null
              },
              {
                  "id": 26,
                  "sortId": 3,
                  "labelName": "SpringCloud",
                  "labelDescription": "SpringCloud",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              {
                  "id": 27,
                  "sortId": 3,
                  "labelName": "MyBatis",
                  "labelDescription": "MyBatis",
                  "goodId": null,
                  "countOfLabel": 2,
                  "goodInfo": null
              },
              {
                  "id": 28,
                  "sortId": 3,
                  "labelName": "MQ",
                  "labelDescription": "MQ",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              }
          ]
      },
      {
          "id": 4,
          "sortName": "寻国记",
          "sortDescription": "你看这世界多奇妙",
          "sortType": 1,
          "priority": 3,
          "countOfSort": 4,
          "labels": [
              {
                  "id": 11,
                  "sortId": 4,
                  "labelName": "俄罗斯与乌克兰",
                  "labelDescription": "俄罗斯与乌克兰",
                  "goodId": null,
                  "countOfLabel": 3,
                  "goodInfo": null
              },
              {
                  "id": 18,
                  "sortId": 4,
                  "labelName": "儒释道",
                  "labelDescription": "儒释道",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              }
          ]
      },
      {
          "id": 5,
          "sortName": "视听盛宴",
          "sortDescription": "听音乐，看书，看电影",
          "sortType": 0,
          "priority": 2,
          "countOfSort": 19,
          "labels": [
              {
                  "id": 12,
                  "sortId": 5,
                  "labelName": "电影最TOP",
                  "labelDescription": "电影最TOP",
                  "goodId": null,
                  "countOfLabel": 0,
                  "goodInfo": null
              },
              {
                  "id": 13,
                  "sortId": 5,
                  "labelName": "动漫最TOP",
                  "labelDescription": "动漫最TOP",
                  "goodId": null,
                  "countOfLabel": 2,
                  "goodInfo": null
              },
              {
                  "id": 14,
                  "sortId": 5,
                  "labelName": "万卷书",
                  "labelDescription": "万卷书",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              {
                  "id": 19,
                  "sortId": 5,
                  "labelName": "西游记",
                  "labelDescription": "西游记",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              {
                  "id": 21,
                  "sortId": 5,
                  "labelName": "八次危机",
                  "labelDescription": "八次危机",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              {
                  "id": 22,
                  "sortId": 5,
                  "labelName": "我们应该怎样活着",
                  "labelDescription": "我们应该怎样活着",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              {
                  "id": 37,
                  "sortId": 5,
                  "labelName": "搞笑最TOP",
                  "labelDescription": "搞笑最TOP",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              {
                  "id": 38,
                  "sortId": 5,
                  "labelName": "音乐最TOP",
                  "labelDescription": "音乐最TOP",
                  "goodId": null,
                  "countOfLabel": 0,
                  "goodInfo": null
              }
          ]
      },
      {
          "id": 6,
          "sortName": "POETIZE",
          "sortDescription": "最美博客",
          "sortType": 0,
          "priority": 5,
          "countOfSort": 16,
          "labels": [
              {
                  "id": 30,
                  "sortId": 6,
                  "labelName": "部署文档",
                  "labelDescription": "部署文档",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              {
                  "id": 31,
                  "sortId": 6,
                  "labelName": "使用指南",
                  "labelDescription": "使用指南",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              }
          ]
      },
      {
          "id": 7,
          "sortName": "资源",
          "sortDescription": "寻找有趣的资源",
          "sortType": 0,
          "priority": 6,
          "countOfSort": 7,
          "labels": [
              {
                  "id": 32,
                  "sortId": 7,
                  "labelName": "图片",
                  "labelDescription": "图片",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              {
                  "id": 33,
                  "sortId": 7,
                  "labelName": "影视",
                  "labelDescription": "影视",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              {
                  "id": 34,
                  "sortId": 7,
                  "labelName": "小说",
                  "labelDescription": "小说",
                  "goodId": null,
                  "countOfLabel": 0,
                  "goodInfo": null
              },
              {
                  "id": 35,
                  "sortId": 7,
                  "labelName": "游戏",
                  "labelDescription": "游戏",
                  "goodId": null,
                  "countOfLabel": 0,
                  "goodInfo": null
              },
              {
                  "id": 39,
                  "sortId": 7,
                  "labelName": "测试付费专栏",
                  "labelDescription": "测试付费专栏",
                  "goodId": "1824313743326642176",
                  "countOfLabel": 4,
                  "goodInfo": {
                      "id": "1824313743326642176",
                      "userId": 1,
                      "type": "label",
                      "userLv": null,
                      "articleId": null,
                      "labelId": 39,
                      "title": "测试付费专栏",
                      "subTitle": "测试付费专栏",
                      "stock": 999,
                      "soldOut": 1,
                      "goodCover": "https://file.poetize.cn/randomCover/Sara11712577250859470.jpg",
                      "price": 1.00,
                      "originalPrice": 2.00,
                      "tips": "感恩回馈",
                      "memberFree": false,
                      "status": true,
                      "createTime": "2024-08-16 13:14:25",
                      "updateTime": "2024-08-29 04:00:00",
                      "updateBy": null,
                      "articleTitle": null,
                      "labelName": null
                  }
              },
              {
                  "id": 40,
                  "sortId": 7,
                  "labelName": "测试付费商品",
                  "labelDescription": "测试付费商品",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              }
          ]
      }
  ],
  "currentTimeMillis": 1725092085704
}
Mock.mock("/webInfo/getSortInfo", getSortJson)

let artIcleJson = {
  "code": 200,
  "message": null,
  "data": {
      "2": [
          {
              "id": 108,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11722466015637477.jpg",
              "articleTitle": "转载 | 大梦 & 漫长的季节",
              "articleContent": " 转载自：B站 - 钢镚小豆豆\n这才是人生！【大梦 & 漫长的季节】超还原剧情完整MV 【范伟&瓦依那_任素汐】（无观众声）（钢镚小豆豆自制）",
              "viewCount": 606,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-08-01 06:49:04",
              "updateTime": "2024-08-01 06:49:04",
              "updateBy": null,
              "sortId": 2,
              "labelId": 20,
              "commentCount": 2,
              "username": "Sara",
              "sort": {
                  "id": 2,
                  "sortName": "生活倒影",
                  "sortDescription": "记录美好生活",
                  "sortType": 0,
                  "priority": 1,
                  "countOfSort": 9,
                  "labels": null
              },
              "label": {
                  "id": 20,
                  "sortId": 2,
                  "labelName": "人间百态",
                  "labelDescription": "人间百态",
                  "goodId": null,
                  "countOfLabel": 3,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 107,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11719987054945367.jpg",
              "articleTitle": "差不多先生",
              "articleContent": " 好运与坏运\n上半年偶然碰到一个面试，很顺利的通过了，待遇也还不错。然后我跑了很远去参加线下终面。开场面试官说我的冲锋衣外套的领口竖起来了，注意仪容仪表。",
              "viewCount": 1292,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-07-03 14:21:20",
              "updateTime": "2024-07-03 14:21:20",
              "updateBy": null,
              "sortId": 2,
              "labelId": 6,
              "commentCount": 6,
              "username": "Sara",
              "sort": {
                  "id": 2,
                  "sortName": "生活倒影",
                  "sortDescription": "记录美好生活",
                  "sortType": 0,
                  "priority": 1,
                  "countOfSort": 9,
                  "labels": null
              },
              "label": {
                  "id": 6,
                  "sortId": 2,
                  "labelName": "被偷走的那几年",
                  "labelDescription": "被偷走的那几年",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 106,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11719916284944947.jpg",
              "articleTitle": "马喽的命也是命",
              "articleContent": " 【马喽的命】嘲笑马喽，理解马喽，成为马喽\n<div style=\"position: relative;width: 100%;padding-botto",
              "viewCount": 945,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-07-02 18:32:11",
              "updateTime": "2024-07-02 18:54:33",
              "updateBy": "Sara",
              "sortId": 2,
              "labelId": 20,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 2,
                  "sortName": "生活倒影",
                  "sortDescription": "记录美好生活",
                  "sortType": 0,
                  "priority": 1,
                  "countOfSort": 9,
                  "labels": null
              },
              "label": {
                  "id": 20,
                  "sortId": 2,
                  "labelName": "人间百态",
                  "labelDescription": "人间百态",
                  "goodId": null,
                  "countOfLabel": 3,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 104,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11718441575700330.jpg",
              "articleTitle": "【免费抽奖】黑神话悟空&POETIZE授权",
              "articleContent": " 【POETIZE】两周年抽奖活动\n参与方式：`下方留言`\n\n开奖日期：`2024年8月21日`\n\n奖品：\n- 一等奖：一个`黑神话悟空 - 直面天命`\n",
              "viewCount": 2881,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": "comment",
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-15 17:28:51",
              "updateTime": "2024-06-16 04:16:22",
              "updateBy": "Sara",
              "sortId": 2,
              "labelId": 6,
              "commentCount": 279,
              "username": "Sara",
              "sort": {
                  "id": 2,
                  "sortName": "生活倒影",
                  "sortDescription": "记录美好生活",
                  "sortType": 0,
                  "priority": 1,
                  "countOfSort": 9,
                  "labels": null
              },
              "label": {
                  "id": 6,
                  "sortId": 2,
                  "labelName": "被偷走的那几年",
                  "labelDescription": "被偷走的那几年",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 96,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11717229176891520.jpg",
              "articleTitle": "我就算没了工作，我也不能辜负你妈",
              "articleContent": "苦尽甘来，人间有情。",
              "viewCount": 1385,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-01 16:10:44",
              "updateTime": "2024-06-01 16:10:44",
              "updateBy": null,
              "sortId": 2,
              "labelId": 6,
              "commentCount": 5,
              "username": "Sara",
              "sort": {
                  "id": 2,
                  "sortName": "生活倒影",
                  "sortDescription": "记录美好生活",
                  "sortType": 0,
                  "priority": 1,
                  "countOfSort": 9,
                  "labels": null
              },
              "label": {
                  "id": 6,
                  "sortId": 2,
                  "labelName": "被偷走的那几年",
                  "labelDescription": "被偷走的那几年",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 93,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11715508034407890.jpg",
              "articleTitle": "人生第一个母亲节",
              "articleContent": "有感而发，今天宝宝55天整了！\n回想整个孕期到现在，真的是很快啊，不到一年的时间，已经由二人世界变为一家三口了！\n\n 十月怀胎篇\n都说十月怀胎很辛苦，这个",
              "viewCount": 2280,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-05-12 18:00:49",
              "updateTime": "2024-05-12 23:29:43",
              "updateBy": "Sara",
              "sortId": 2,
              "labelId": 6,
              "commentCount": 8,
              "username": "Sara",
              "sort": {
                  "id": 2,
                  "sortName": "生活倒影",
                  "sortDescription": "记录美好生活",
                  "sortType": 0,
                  "priority": 1,
                  "countOfSort": 9,
                  "labels": null
              },
              "label": {
                  "id": 6,
                  "sortId": 2,
                  "labelName": "被偷走的那几年",
                  "labelDescription": "被偷走的那几年",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          }
      ],
      "5": [
          {
              "id": 103,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11717819175488888.jpg",
              "articleTitle": "转载 | 过去&未来",
              "articleContent": " 转载自：B站 - 今夜流星小铺\n2022最后一天，我接到了来自四年前的电话...... | 2022关于我的一切",
              "viewCount": 521,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-08 12:10:48",
              "updateTime": "2024-06-08 12:10:48",
              "updateBy": null,
              "sortId": 5,
              "labelId": 22,
              "commentCount": 2,
              "username": "Sara",
              "sort": {
                  "id": 5,
                  "sortName": "视听盛宴",
                  "sortDescription": "听音乐，看书，看电影",
                  "sortType": 0,
                  "priority": 2,
                  "countOfSort": 19,
                  "labels": null
              },
              "label": {
                  "id": 22,
                  "sortId": 5,
                  "labelName": "我们应该怎样活着",
                  "labelDescription": "我们应该怎样活着",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 102,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11717817313060387.jpg",
              "articleTitle": "转载 | 不是三块买不起！！只是四块更有性价比！",
              "articleContent": " 转载自：B站 - 熬一耶ye",
              "viewCount": 345,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-08 11:32:07",
              "updateTime": "2024-06-08 11:34:23",
              "updateBy": "Sara",
              "sortId": 5,
              "labelId": 37,
              "commentCount": 3,
              "username": "Sara",
              "sort": {
                  "id": 5,
                  "sortName": "视听盛宴",
                  "sortDescription": "听音乐，看书，看电影",
                  "sortType": 0,
                  "priority": 2,
                  "countOfSort": 19,
                  "labels": null
              },
              "label": {
                  "id": 37,
                  "sortId": 5,
                  "labelName": "搞笑最TOP",
                  "labelDescription": "搞笑最TOP",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 83,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11706322622923153.png",
              "articleTitle": "你要多努力，才配拥有生活！",
              "articleContent": "选择放弃梦想，还是为梦想竭尽全力\n\n可是很多时候，只会感受到生活的压力，也从未有过梦想\n\n我们真正想要什么呢\n\n或许迷茫者、痛苦着、艰难者前行，一点一点走出迷茫",
              "viewCount": 3353,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-01-27 10:43:32",
              "updateTime": "2024-01-27 10:43:32",
              "updateBy": null,
              "sortId": 5,
              "labelId": 22,
              "commentCount": 4,
              "username": "Sara",
              "sort": {
                  "id": 5,
                  "sortName": "视听盛宴",
                  "sortDescription": "听音乐，看书，看电影",
                  "sortType": 0,
                  "priority": 2,
                  "countOfSort": 19,
                  "labels": null
              },
              "label": {
                  "id": 22,
                  "sortId": 5,
                  "labelName": "我们应该怎样活着",
                  "labelDescription": "我们应该怎样活着",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 81,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11705406519829572.webp",
              "articleTitle": "你，要怎样度过这一生？",
              "articleContent": "励志短片《不负此生》",
              "viewCount": 1111,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-01-16 20:02:31",
              "updateTime": "2024-01-16 20:02:31",
              "updateBy": null,
              "sortId": 5,
              "labelId": 22,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 5,
                  "sortName": "视听盛宴",
                  "sortDescription": "听音乐，看书，看电影",
                  "sortType": 0,
                  "priority": 2,
                  "countOfSort": 19,
                  "labels": null
              },
              "label": {
                  "id": 22,
                  "sortId": 5,
                  "labelName": "我们应该怎样活着",
                  "labelDescription": "我们应该怎样活着",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 71,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11702636809491337.jpg",
              "articleTitle": "朝阳冬泳怪鸽 - 正能量奥利给励志视频",
              "articleContent": "我是，辽宁朝阳，冬泳怪鸽。\n我这人很怪————四一的脚，穿四五的鞋；一年四季不穿袜子。\n“鸽”呢，是鸽子的鸽，它是和平的象征。\n\n有的人说我是傻子，说我疯了",
              "viewCount": 834,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2023-12-15 18:54:44",
              "updateTime": "2024-01-09 15:32:34",
              "updateBy": null,
              "sortId": 5,
              "labelId": 22,
              "commentCount": 3,
              "username": "Sara",
              "sort": {
                  "id": 5,
                  "sortName": "视听盛宴",
                  "sortDescription": "听音乐，看书，看电影",
                  "sortType": 0,
                  "priority": 2,
                  "countOfSort": 19,
                  "labels": null
              },
              "label": {
                  "id": 22,
                  "sortId": 5,
                  "labelName": "我们应该怎样活着",
                  "labelDescription": "我们应该怎样活着",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          },
          {
              "id": 70,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11702635346095705.jpg",
              "articleTitle": "《看见》演讲人：黄春生",
              "articleContent": "不要冷漠的走入普通人。\n那些不加思索就说这里不够潮的人。\n应该亲自来这里看看。\n有人在大山里起舞。\n有人在菜地里高歌。\n有人潜入最深的海底。\n有人登上最高的山",
              "viewCount": 706,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2023-12-15 18:28:54",
              "updateTime": "2024-01-09 12:20:51",
              "updateBy": null,
              "sortId": 5,
              "labelId": 22,
              "commentCount": 2,
              "username": "Sara",
              "sort": {
                  "id": 5,
                  "sortName": "视听盛宴",
                  "sortDescription": "听音乐，看书，看电影",
                  "sortType": 0,
                  "priority": 2,
                  "countOfSort": 19,
                  "labels": null
              },
              "label": {
                  "id": 22,
                  "sortId": 5,
                  "labelName": "我们应该怎样活着",
                  "labelDescription": "我们应该怎样活着",
                  "goodId": null,
                  "countOfLabel": 6,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          }
      ],
      "6": [
          {
              "id": 105,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11719543212884964.jpg",
              "articleTitle": "POETIZE - 宝塔部署教程（兼容其他网站）",
              "articleContent": "加密文章",
              "viewCount": 899,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": "【完整版】限时折扣，您将获得：部署文档、技术支持和POETIZE交流群。详情请访问【https://poetize.cn/article/20】。",
              "viewType": "userLv",
              "subViewValue": null,
              "subTips": null,
              "subViewType": "comment",
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-28 11:18:48",
              "updateTime": "2024-06-28 11:32:40",
              "updateBy": "Sara",
              "sortId": 6,
              "labelId": 30,
              "commentCount": 26,
              "username": "Sara",
              "sort": {
                  "id": 6,
                  "sortName": "POETIZE",
                  "sortDescription": "最美博客",
                  "sortType": 0,
                  "priority": 5,
                  "countOfSort": 16,
                  "labels": null
              },
              "label": {
                  "id": 30,
                  "sortId": 6,
                  "labelName": "部署文档",
                  "labelDescription": "部署文档",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 100,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11718027163532836.jpg",
              "articleTitle": "POETIZE - 文档导航与网站美化",
              "articleContent": " 部署\n![部署.jpg](https://file.poetize.cn/articlePicture/Sara11717458939228739.jp",
              "viewCount": 5386,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": true,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-04 08:36:03",
              "updateTime": "2024-08-31 09:26:33",
              "updateBy": "Sara",
              "sortId": 6,
              "labelId": 31,
              "commentCount": 3,
              "username": "Sara",
              "sort": {
                  "id": 6,
                  "sortName": "POETIZE",
                  "sortDescription": "最美博客",
                  "sortType": 0,
                  "priority": 5,
                  "countOfSort": 16,
                  "labels": null
              },
              "label": {
                  "id": 31,
                  "sortId": 6,
                  "labelName": "使用指南",
                  "labelDescription": "使用指南",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 98,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11717301378901990.jpg",
              "articleTitle": "POETIZE - 常见问题",
              "articleContent": "加密文章",
              "viewCount": 576,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": "【完整版】限时折扣，您将获得：部署文档、技术支持和POETIZE交流群。详情请访问【https://poetize.cn/article/20】。",
              "viewType": "userLv",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-02 12:36:37",
              "updateTime": "2024-08-31 09:20:35",
              "updateBy": "Sara",
              "sortId": 6,
              "labelId": 30,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 6,
                  "sortName": "POETIZE",
                  "sortDescription": "最美博客",
                  "sortType": 0,
                  "priority": 5,
                  "countOfSort": 16,
                  "labels": null
              },
              "label": {
                  "id": 30,
                  "sortId": 6,
                  "labelName": "部署文档",
                  "labelDescription": "部署文档",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 97,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11717294918013489.jpg",
              "articleTitle": "POETIZE - 更新与迁移指南",
              "articleContent": "加密文章",
              "viewCount": 648,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": "【完整版】限时折扣，您将获得：部署文档、技术支持和POETIZE交流群。详情请访问【https://poetize.cn/article/20】。",
              "viewType": "userLv",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-02 11:13:34",
              "updateTime": "2024-08-31 09:15:32",
              "updateBy": "Sara",
              "sortId": 6,
              "labelId": 30,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 6,
                  "sortName": "POETIZE",
                  "sortDescription": "最美博客",
                  "sortType": 0,
                  "priority": 5,
                  "countOfSort": 16,
                  "labels": null
              },
              "label": {
                  "id": 30,
                  "sortId": 6,
                  "labelName": "部署文档",
                  "labelDescription": "部署文档",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 95,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11716558259400677.jpg",
              "articleTitle": "POETIZE - 1Panel部署教程",
              "articleContent": " 前言\n本教程适合对`Docker`有一定了解的用户。\n\n 资源上传\n将压缩包里面的`poetize`文件夹直接上传到`/home`目录下：\n![上",
              "viewCount": 2023,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-05-24 22:09:05",
              "updateTime": "2024-06-28 10:31:55",
              "updateBy": "Sara",
              "sortId": 6,
              "labelId": 30,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 6,
                  "sortName": "POETIZE",
                  "sortDescription": "最美博客",
                  "sortType": 0,
                  "priority": 5,
                  "countOfSort": 16,
                  "labels": null
              },
              "label": {
                  "id": 30,
                  "sortId": 6,
                  "labelName": "部署文档",
                  "labelDescription": "部署文档",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 92,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11714705295099522.png",
              "articleTitle": "POETIZE - Docker部署教程",
              "articleContent": "加密文章",
              "viewCount": 807,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": "【完整版】限时折扣，您将获得：部署文档、技术支持和POETIZE交流群。详情请访问【https://poetize.cn/article/20】。",
              "viewType": "userLv",
              "subViewValue": null,
              "subTips": null,
              "subViewType": "comment",
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-05-03 11:23:32",
              "updateTime": "2024-06-28 10:34:26",
              "updateBy": "Sara",
              "sortId": 6,
              "labelId": 30,
              "commentCount": 17,
              "username": "Sara",
              "sort": {
                  "id": 6,
                  "sortName": "POETIZE",
                  "sortDescription": "最美博客",
                  "sortType": 0,
                  "priority": 5,
                  "countOfSort": 16,
                  "labels": null
              },
              "label": {
                  "id": 30,
                  "sortId": 6,
                  "labelName": "部署文档",
                  "labelDescription": "部署文档",
                  "goodId": null,
                  "countOfLabel": 8,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": null
          }
      ],
      "7": [
          {
              "id": 113,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/randomCover/Sara11712577320021545.jpg",
              "articleTitle": "测试付费专栏的付费文章",
              "articleContent": "加密文章",
              "viewCount": 4,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "pay",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-08-16 13:21:52",
              "updateTime": "2024-08-16 13:21:52",
              "updateBy": null,
              "sortId": 7,
              "labelId": 39,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 7,
                  "sortName": "资源",
                  "sortDescription": "寻找有趣的资源",
                  "sortType": 0,
                  "priority": 6,
                  "countOfSort": 7,
                  "labels": null
              },
              "label": {
                  "id": 39,
                  "sortId": 7,
                  "labelName": "测试付费专栏",
                  "labelDescription": "测试付费专栏",
                  "goodId": "1824313743326642176",
                  "countOfLabel": 4,
                  "goodInfo": {
                      "id": "1824313743326642176",
                      "userId": 1,
                      "type": "label",
                      "userLv": null,
                      "articleId": null,
                      "labelId": 39,
                      "title": "测试付费专栏",
                      "subTitle": "测试付费专栏",
                      "stock": 999,
                      "soldOut": 1,
                      "goodCover": "https://file.poetize.cn/randomCover/Sara11712577250859470.jpg",
                      "price": 1.00,
                      "originalPrice": 2.00,
                      "tips": "感恩回馈",
                      "memberFree": false,
                      "status": true,
                      "createTime": "2024-08-16 13:14:25",
                      "updateTime": "2024-08-29 04:00:00",
                      "updateBy": null,
                      "articleTitle": null,
                      "labelName": null
                  }
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 112,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/randomCover/Sara11712577319942497.jpg",
              "articleTitle": "测试付费专栏的付费文章，并且隐藏资源也需要付费",
              "articleContent": "加密文章",
              "viewCount": 6,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": "1824314327681269760",
              "tips": null,
              "viewType": "pay",
              "subViewValue": null,
              "subTips": null,
              "subViewType": "pay",
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-08-16 13:09:04",
              "updateTime": "2024-08-16 13:09:04",
              "updateBy": null,
              "sortId": 7,
              "labelId": 39,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 7,
                  "sortName": "资源",
                  "sortDescription": "寻找有趣的资源",
                  "sortType": 0,
                  "priority": 6,
                  "countOfSort": 7,
                  "labels": null
              },
              "label": {
                  "id": 39,
                  "sortId": 7,
                  "labelName": "测试付费专栏",
                  "labelDescription": "测试付费专栏",
                  "goodId": "1824313743326642176",
                  "countOfLabel": 4,
                  "goodInfo": {
                      "id": "1824313743326642176",
                      "userId": 1,
                      "type": "label",
                      "userLv": null,
                      "articleId": null,
                      "labelId": 39,
                      "title": "测试付费专栏",
                      "subTitle": "测试付费专栏",
                      "stock": 999,
                      "soldOut": 1,
                      "goodCover": "https://file.poetize.cn/randomCover/Sara11712577250859470.jpg",
                      "price": 1.00,
                      "originalPrice": 2.00,
                      "tips": "感恩回馈",
                      "memberFree": false,
                      "status": true,
                      "createTime": "2024-08-16 13:14:25",
                      "updateTime": "2024-08-29 04:00:00",
                      "updateBy": null,
                      "articleTitle": null,
                      "labelName": null
                  }
              },
              "hasVideo": false,
              "goodInfo": {
                  "id": "1824314327681269760",
                  "userId": 1,
                  "type": "article",
                  "userLv": null,
                  "articleId": 112,
                  "labelId": null,
                  "title": "测试付费专栏的付费文章，并且隐藏资源也需要付费",
                  "subTitle": "测试付费专栏的付费文章，并且隐藏资源也需要付费",
                  "stock": -1,
                  "soldOut": 0,
                  "goodCover": "https://file.poetize.cn/randomCover/Sara11712577319942497.jpg",
                  "price": 2.00,
                  "originalPrice": 1.00,
                  "tips": "乞讨",
                  "memberFree": false,
                  "status": true,
                  "createTime": "2024-08-16 13:16:44",
                  "updateTime": "2024-08-28 21:33:12",
                  "updateBy": null,
                  "articleTitle": null,
                  "labelName": null
              }
          },
          {
              "id": 111,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/randomCover/Sara11712577250984979.jpg",
              "articleTitle": "测试付费专栏的免费文章，但是隐藏资源需要付费",
              "articleContent": "测试付费专栏的免费文章，但是隐藏资源需要付费",
              "viewCount": 53,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": "1824316686889189376",
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": "pay",
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-08-16 13:06:39",
              "updateTime": "2024-08-16 13:21:23",
              "updateBy": null,
              "sortId": 7,
              "labelId": 39,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 7,
                  "sortName": "资源",
                  "sortDescription": "寻找有趣的资源",
                  "sortType": 0,
                  "priority": 6,
                  "countOfSort": 7,
                  "labels": null
              },
              "label": {
                  "id": 39,
                  "sortId": 7,
                  "labelName": "测试付费专栏",
                  "labelDescription": "测试付费专栏",
                  "goodId": "1824313743326642176",
                  "countOfLabel": 4,
                  "goodInfo": {
                      "id": "1824313743326642176",
                      "userId": 1,
                      "type": "label",
                      "userLv": null,
                      "articleId": null,
                      "labelId": 39,
                      "title": "测试付费专栏",
                      "subTitle": "测试付费专栏",
                      "stock": 999,
                      "soldOut": 1,
                      "goodCover": "https://file.poetize.cn/randomCover/Sara11712577250859470.jpg",
                      "price": 1.00,
                      "originalPrice": 2.00,
                      "tips": "感恩回馈",
                      "memberFree": false,
                      "status": true,
                      "createTime": "2024-08-16 13:14:25",
                      "updateTime": "2024-08-29 04:00:00",
                      "updateBy": null,
                      "articleTitle": null,
                      "labelName": null
                  }
              },
              "hasVideo": false,
              "goodInfo": {
                  "id": "1824316686889189376",
                  "userId": 1,
                  "type": "article",
                  "userLv": null,
                  "articleId": 111,
                  "labelId": null,
                  "title": "测试付费专栏的免费文章，但是隐藏资源需要付费",
                  "subTitle": "测试付费专栏的免费文章，但是隐藏资源需要付费",
                  "stock": -1,
                  "soldOut": 0,
                  "goodCover": "https://file.poetize.cn/randomCover/Sara11712577250984979.jpg",
                  "price": 2.00,
                  "originalPrice": null,
                  "tips": null,
                  "memberFree": false,
                  "status": true,
                  "createTime": "2024-08-16 13:26:06",
                  "updateTime": "2024-08-30 13:00:00",
                  "updateBy": null,
                  "articleTitle": null,
                  "labelName": null
              }
          },
          {
              "id": 110,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/randomCover/Sara11712577250907813.jpg",
              "articleTitle": "测试付费专栏的免费文章",
              "articleContent": "测试付费专栏的免费文章",
              "viewCount": 43,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": null,
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-08-16 13:05:31",
              "updateTime": "2024-08-16 13:05:31",
              "updateBy": null,
              "sortId": 7,
              "labelId": 39,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 7,
                  "sortName": "资源",
                  "sortDescription": "寻找有趣的资源",
                  "sortType": 0,
                  "priority": 6,
                  "countOfSort": 7,
                  "labels": null
              },
              "label": {
                  "id": 39,
                  "sortId": 7,
                  "labelName": "测试付费专栏",
                  "labelDescription": "测试付费专栏",
                  "goodId": "1824313743326642176",
                  "countOfLabel": 4,
                  "goodInfo": {
                      "id": "1824313743326642176",
                      "userId": 1,
                      "type": "label",
                      "userLv": null,
                      "articleId": null,
                      "labelId": 39,
                      "title": "测试付费专栏",
                      "subTitle": "测试付费专栏",
                      "stock": 999,
                      "soldOut": 1,
                      "goodCover": "https://file.poetize.cn/randomCover/Sara11712577250859470.jpg",
                      "price": 1.00,
                      "originalPrice": 2.00,
                      "tips": "感恩回馈",
                      "memberFree": false,
                      "status": true,
                      "createTime": "2024-08-16 13:14:25",
                      "updateTime": "2024-08-29 04:00:00",
                      "updateBy": null,
                      "articleTitle": null,
                      "labelName": null
                  }
              },
              "hasVideo": false,
              "goodInfo": null
          },
          {
              "id": 109,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/randomCover/Sara1171257732029155.jpg",
              "articleTitle": "测试付费商品",
              "articleContent": "付费后才能看到隐藏资源",
              "viewCount": 70,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": "1824313271236755456",
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": "pay",
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-08-16 13:04:30",
              "updateTime": "2024-08-16 13:04:30",
              "updateBy": null,
              "sortId": 7,
              "labelId": 40,
              "commentCount": 0,
              "username": "Sara",
              "sort": {
                  "id": 7,
                  "sortName": "资源",
                  "sortDescription": "寻找有趣的资源",
                  "sortType": 0,
                  "priority": 6,
                  "countOfSort": 7,
                  "labels": null
              },
              "label": {
                  "id": 40,
                  "sortId": 7,
                  "labelName": "测试付费商品",
                  "labelDescription": "测试付费商品",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              "hasVideo": false,
              "goodInfo": {
                  "id": "1824313271236755456",
                  "userId": 1,
                  "type": "article",
                  "userLv": null,
                  "articleId": 109,
                  "labelId": null,
                  "title": "测试付费商品",
                  "subTitle": "测试付费商品",
                  "stock": -1,
                  "soldOut": 1,
                  "goodCover": "https://file.poetize.cn/randomCover/Sara1171257732029155.jpg",
                  "price": 1.00,
                  "originalPrice": 2.00,
                  "tips": "夏末特惠",
                  "memberFree": false,
                  "status": true,
                  "createTime": "2024-08-16 13:12:32",
                  "updateTime": "2024-08-31 16:00:00",
                  "updateBy": null,
                  "articleTitle": null,
                  "labelName": null
              }
          },
          {
              "id": 101,
              "userId": 1,
              "articleCover": "https://file.poetize.cn/articleCover/Sara11717752723657534.webp",
              "articleTitle": "范马刃牙VS拳愿阿修罗",
              "articleContent": "不可思议的联名合作，梦幻对决终于登场！\n\n《刃牙》漫画系列原于秋田书店的《周刊少年 Champion》连载，这部热销格斗漫画狂卖超过 8500 万册，描绘众多",
              "viewCount": 329,
              "likeCount": 0,
              "commentStatus": true,
              "status": true,
              "recommendStatus": false,
              "videoUrl": null,
              "viewValue": null,
              "goodId": null,
              "tips": null,
              "viewType": "public",
              "subViewValue": null,
              "subTips": null,
              "subViewType": "comment",
              "subContent": null,
              "downloadStatus": false,
              "createTime": "2024-06-07 17:32:29",
              "updateTime": "2024-06-07 17:32:29",
              "updateBy": null,
              "sortId": 7,
              "labelId": 33,
              "commentCount": 9,
              "username": "Sara",
              "sort": {
                  "id": 7,
                  "sortName": "资源",
                  "sortDescription": "寻找有趣的资源",
                  "sortType": 0,
                  "priority": 6,
                  "countOfSort": 7,
                  "labels": null
              },
              "label": {
                  "id": 33,
                  "sortId": 7,
                  "labelName": "影视",
                  "labelDescription": "影视",
                  "goodId": null,
                  "countOfLabel": 1,
                  "goodInfo": null
              },
              "hasVideo": true,
              "goodInfo": null
          }
      ]
  },
  "currentTimeMillis": 1725092086152
}
Mock.mock("/article/listSortArticle", getSortJson)
let getAdmireJson = {

}
Mock.mock("/webInfo/getAdmire", getAdmireJson)
